PostgreSQL:
  restart: always
  image: sameersbn/postgresql:10-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
